# Generated by Django 5.0.4 on 2024-04-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JE_Code', models.CharField(max_length=8, null=True)),
                ('Store', models.CharField(default=False, max_length=20)),
                ('Country', models.CharField(max_length=20, null=True)),
                ('Region', models.CharField(default=False, max_length=20)),
                ('Item', models.CharField(max_length=50, null=True)),
                ('List_Price', models.IntegerField(null=True)),
                ('Actual_Price', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
            ],
        ),
    ]
