# Generated by Django 5.0.4 on 2024-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SouthSideUserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='Salesperson',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
