# Generated by Django 5.0.4 on 2024-05-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QATrackOneApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_models',
            name='Date',
        ),
    ]
