# Generated by Django 5.0.4 on 2024-04-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('JE_Code', models.CharField(primary_key=True, max_length=8, null=True)),
                ('Store', models.CharField(max_length=20, null=True)),
                ('Country', models.CharField(max_length=20, null=True)),
                ('Region', models.CharField(max_length=20, null=True)),
                ('Date', models.DateField(null=True)),
                ('Item', models.CharField(max_length=50)),
                ('List_Price', models.IntegerField(null=True)),
                ('Actual_Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
