# Generated by Django 5.0.4 on 2024-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SouthSideApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='Actual_Price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='Date',
            field=models.DateField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='Region',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='Store',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
