# Generated by Django 5.0.4 on 2024-04-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SouthSideApp', '0002_alter_collectionmodel_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='Date',
        ),
    ]
