# Generated by Django 5.0.4 on 2024-04-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SouthSideApp', '0003_remove_collectionmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='Item',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
